spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#  cloud:
#    gateway:
##      default-filters:
##        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowed-origins: "http://172.21.1.126:8080"
#            allowed-methods: "*"
#            allowed-headers: "*"
#            allow-credentials: true
#  security:
#    user:
#      name: admin
#      password: admin
#  redis:
#    database: 0
#    host: 172.23.20.101
#    port: 6379
server:
  port: 8765

eureka:
  client:
    service-url: 
#      defaultZone: http://172.23.20.101:8761/eureka
      defaultZone: http://localhost:8761/eureka
  